name: revalidate
on:
  schedule:
    - cron: '*/50 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url '${{secrets.Revalidate_URL}}' \
